version: "2.1"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    tty: true
    stdin_open: true
    depends_on:
      - 'mongo'
    build: .
    ports:
      - 3001:3000