name: Shell Commands # Name

on: [push] # Event

jobs:
  run-shell-command: # nombre del job
    runs-on: ubuntu-latest # sistema operativo
    steps: # pasos
      - name: echo a string # nombre del paso
        run: echo "Hello World" # ejecucion
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python # podemos usar el bash de python
  run-windwos-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] # primero se ejecuta run-shell-command, luego este
    steps:
      - name: Directory PowerShell
        run: Get-Location 
      - name: Directory Bash 
        run: pwd 
        shell: bash  # podemos usar el bash de ubuntu, por defecto en windows es powershell