name: Matrix 
on: push 

jobs: 
  node-version:
    strategy: 
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # va a generar un job por cada uno
        node_version: [6, 8, 10]  # va a generar un job por cada uno
        include: 
          - os: ubuntu-latest
            node_version: 8
            is_ubuntu_8: "true" # solo la inserta en lo especificado arriba
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
    runs-on: ${{ matrix.os }}
    env: 
      IS_UBUNTU_8: ${{ matrix.is_ubuntu_8 }}
    steps: 
      - name: Log node version 
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }} # usamos la env que usamos en matrix
      - name: Log node version 
        run:  | 
          node -v
          echo $IS_UBUNTU_8