name: Container
on: push

jobs: 
  local-node-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cd simple-docker-nodejs-api-master
          docker-compose build
          docker-compose up -d
      - name: SHIT
        run: docker ps 
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users
  local-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 4.2
          mongodb-replica-set: test-rs
          mongodb-port: 27017
          mongodb-db: users
      - name: Install PM2
        run: npm i pm2 -g
      - name: local node test
        run: |
          cd simple-docker-nodejs-api-master
          npm install
          pm2 start app.js
        env:
          CI: true
      - name: pija
        run: pm2 list    
      - name: Post a user
        run: 'curl -X POST http://localhost:3000/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3000/api/users
      - name: puta madre
        if: always()
        run: pm2 logs --nostream 


  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: 'curl -X POST http://localhost:3001/api/user -H ''Content-Type: application/json'' -d ''{"username": "hello","address": "dwded"}'''
      - name: Get Users
        run: curl http://localhost:3001/api/users